### ISSUE TITLE
Add PS+ commands undo, quit, and goto

### ISSUE THREAD

**Issue by david-pfx** [ClementSparrow/Pattern-Script#64]
Broadly compatible with PS+.
* undo - as per Z key
* quit - as per Escape
* nosave - already done
Also possibly:
* goto <level> - similar to PS+, not identical

**Comment by ClementSparrow** [comment]
What are the use cases for these commands? Especially `undo` and `quit`?
Also, Escape currently opens the menu, so what would `quit` do?
As for `goto`, I think it should not be a command because we don't want to mix concerns in the RULES section about level progression structure and mechanics. I think it deserves a different approach.

**Comment by david-pfx** [comment]
They serve exactly the same purpose as in PS+, so the primary intent is compatibility. 
In PS+ Undo and Quit replicate the functions of keystrokes Z and Escape so that they can be attached to buttons in a mouse-only or touch-only game.
GOTO is easy to do and looks useful, but if you are unsure you should ask PS+ users what they see in it. Meanwhile I don't see a design for a 'different approach', so maybe it's just better than nothing.

**Comment by ClementSparrow** [comment]
Then I must state again that the objective of Pattern:Script is not to be compatible with PS+. I understand the value of having a PS+/P:S compatible system, but I think this should be a separate fork, not something to add to P:S. So, I'm closing the issue for the moment.
